### ISSUE TITLE
PredictAPI not completed

### ISSUE THREAD

**Issue by jjanousek** [IBM/MAX-Framework#37]
I am working with the MAX-Audio-Classifier and I am trying to understand the PredictAPI that is imported from maxfw.core in the [predict.py](https://github.com/IBM/MAX-Audio-Classifier/blob/master/api/predict.py) file.
When checking the maxfw.core repo I find that the PredictAPI is not implemented. 

Have I missed the PredictAPI or how does the audio-classifier import and use the PredictAPI if it has not been implemented yet?

Thanks,
Johannes

**Comment by jjanousek** [comment]
I see that the model uses the [max-base image](https://quay.io/repository/codait/max-base?tab=info) with pre-installed maxfw. Could it be that the image was built with a different version of maxfw than the one visible on github?

**Comment by bdwyer2** [comment]
cc @kmh4321

**Comment by kmh4321** [comment]
Hello @jjanousek 
Thank you for your interest in MAX. 
The PredictAPI is just an empty abstract class. The actual prediction function is here: 
https://github.com/IBM/MAX-Audio-Classifier/blob/e78d395820cd4de9955465a274d6803fe99259fb/core/model.py#L86

Hope that helps!

**Comment by jjanousek** [comment]
Thanks, @kmh4321 understand it now.
