### ISSUE TITLE
Add support for 'port' parameter on MAXApp.run() method

### ISSUE THREAD

**Issue by MillerMedia** [IBM/MAX-Framework#39]
In MAX-Framework/maxfw/core/app.py, a Flask app is instantiated. There is a parameter for 'port' that is not available through the abstracted MAXApp.run() method.

It is documented here:
https://flask.palletsprojects.com/en/1.1.x/api/#flask.Flask.run

Perhaps something like this would add support for alternate ports when using MAXApp.run()

`def run(self, host='0.0.0.0', port=5000):
    self.app.run(host, port)`

**Comment by kmh4321** [comment]
Hello @MillerMedia, 
That's a good point. We'll take a look at it and get back to you. Would you like to create a PR to add that?

**Comment by MillerMedia** [comment]
Hi @kmh4321 , PR submitted:
https://github.com/IBM/MAX-Framework/pull/40

**Comment by kmh4321** [comment]
Closed via #40
